### ISSUE TITLE
When invoking `fava-gtk` from terminal, ctrl+c to close app doesn't close fava-gtk window.

### ISSUE THREAD

**Issue by seltzered** [johannesjh/favagtk#13]
If a user does the following steps:

1. starts fava-gtk from a terminal window
2. observes fava-gtk window opens
3. decides to close fava-gtk from terminal window by doing ctrl+c

The fava-gtk window will not close and still be there, frozen.

Seems like there needs to be a event routine to close the window

**Comment by johannesjh** [comment]
I'll close this ticket because I stopped publishing favagtk as python package. Instead, it is published as flatpak application. 

Note: I tested to see if the flatpak application correctly closes when I hit `Ctrl+C` on the commandline, and I found it does.
